const puzzles = [
    {
        puzzleId: 1,
        theme: "Animals",
        answer: ["E", "L", "E", "P", "H", "A", "N", "T"],
        clue1: ["?", "?", "?", "?", "!", "E", "!", "?"],
        clue2: ["?", "!", "!", "O", "P", "!", "R", "D"],
        clue3: ["!", "!", "K", "?", "?", "?", "?", "?"],
        clue4: ["?", "?", "?", "?", "!", "!", "W", "K"],
        clueHints: ["1. A domesticated female bird", "2. Can reach speeds of up to 36 miles per hour", "3. One of the largest species in the deer family", "4. A bird of prey"],
        statusTitle: "Take a guess!",
        encouragement: "You got this!",
        funFact: "Elephants are the largest land animals on Earth!",
    },
    {
        puzzleId: 2,
        theme: "Countries",
        answer: ["M", "A", "L", "A", "Y", "S", "I", "A"],
        clue1: ["!", "!", "!", "T", "A", "?", "?", "?"],
        clue2: ["?", "?", "!", "!", "O", "!", "?", "?"],
        clue3: ["?", "?", "!", "!", "T", "V", "!", "!"],
        clue4: ["?", "!", "!", "G", "E", "R", "!", "!"],
        clueHints: ["1. A European archipelago", "2. This country shares a border with Thailand", "3. The capital of this country is Riga", "4. The tenth largest country by area"],
        statusTitle: "What's your guess?",
        encouragement: "and no looking at any maps!",
        funFact: "70% of the population of Malaysia is urban.",
    },
    {
        puzzleId: 3,
        theme: "Mythical Creatures",
        answer: ["W", "E", "R", "E", "W", "O", "L", "F"],
        clue1: ["?", "?", "?", "?", "?", "E", "!", "!"],
        clue2: ["O", "G", "!", "!", "?", "?", "?", "?"],
        clue3: ["?", "?", "?", "T", "R", "!", "!", "L"],
        clue4: ["N", "!", "!", "!", "I", "D", "?", "?"],
        clueHints: ["1. A pointy-eared humanoid being", "2. A large humanoid being with great strength", "3. A magical creature that lives in the hills", "4. A sea nymph of the Mediterranean"],
        statusTitle: "and your answer is...",
        encouragement: "...don't worry, I'm patient.",
        funFact: "A werewolf's transformation is often associated with the appearance of a full moon.",
    },
    {
        puzzleId: 4,
        theme: "Musical Instruments",
        answer: ["M", "A", "N", "D", "O", "L", "I", "N"],
        clue1: ["?", "?", "V", "I", "!", "!", "!", "!"],
        clue2: ["B", "!", "!", "J", "!", "?", "?", "?"],
        clue3: ["H", "!", "!", "!", "P", "A", "N", "?"],
        clue4: ["?", "?", "O", "B", "!", "E", "?", "?"],
        clueHints: ["1. A four-stringed instrument", "2. A five-stringed instrument", "3. A subset of steelpan instruments", "4. A double-reed woodwind instrument"],
        statusTitle: "Compose an Answer...",
        encouragement: "...or just play it by ear.",
        funFact: "While a violin has four strings and a banjo has five, a mandolin has eight!",
    },
    {
        puzzleId: 5,
        theme: "Metals",
        answer: ["A", "L", "U", "M", "I", "N", "U", "M"],
        clue1: ["?", "?", "?", "Z", "!", "!", "C", "?"],
        clue2: ["?", "?", "?", "T", "!", "!", "?", "?"],
        clue3: ["?", "!", "I", "T", "H", "I", "!", "!"],
        clue4: ["!", "!", "L", "O", "Y", "?", "?", "?"],
        clueHints: ["1. This metal is good for your immune system", "2. Pewter is almost entirely composed of this", "3. This metal has an atomic number of 3", "4. A composition of two or more metals"],
        statusTitle: "F",
        encouragement: "...or just play it by ear.",
        funFact: "Aluminum is the third most abundant element in the earth's crust, after oxygen and silicon.",
    },
    {
        puzzleId: 6,
        theme: "Occupations",
        answer: ["M", "E", "C", "H", "A", "N", "I", "C"],
        clue1: ["?", "?", "!", "L", "E", "R", "!", "!"],
        clue2: ["?", "?", "!", "!", "E", "F", "?", "?"],
        clue3: ["!", "!", "D", "I", "C", "?", "?", "?"],
        clue4: ["?", "?", "!", "R", "I", "T", "!", "!"],
        clueHints: ["1. A religious leader or priest", "2. Trained in food preparation", "3. Administers first-aid at combat sites", "4. Someone who judges artwork professionally"],
        statusTitle: "Think of something...",
        encouragement: "...or you're fired!",
        funFact: "Queen Elizabeth II trained to be a mechanic and truck driver during WWII.",
    },
];

export default puzzles;